---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[reapr::default]
    attributes:
