default['reapr']['version'] = '1.0.18'
default['reapr']['install_path'] = '/usr/local'
default['reapr']['dirname'] = 'Reapr_' + default['reapr']['version']
default['reapr']['filename'] = "Reapr_#{node['reapr']['version']}.tar.gz"
default['reapr']['url_root'] = 'ftp://ftp.sanger.ac.uk/pub/resources/software/reapr'
default['reapr']['url'] = "#{node['reapr']['url_root']}/#{node['reapr']['filename']}"
default['reapr']['test_data'] = "Reapr_#{node['reapr']['version']}.test_data.tar.gz"
default['reapr']['test_data_url'] = "#{node['reapr']['url_root']}/#{node['reapr']['test_data']}"
default['reapr']['test_data_path'] = "#{node['reapr']['install_pathi']}/#{node['reapr']['dirname']}/Reapr_#{node['reapr']['version']}.test_data/"
